name: Beachbol update hour
on:
  schedule:
    - cron: "1 * * * *"
  workflow_dispatch:
jobs:
  update-hour:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Get current reservation hour
        id: hour
        run: |
          a=$(curl -s -XGET https://beachbol.beachliga.com | grep window._rop)
          a="${a#*\'}"
          a="${a%\'*}"
          echo $a > hour
          updated=$(git diff hour | wc -l)
          if [ $updated -gt 0 ]
          then
            echo $(date) > updated
            git add updated
            git add hour
            git commit -m "Update hour"
            git push
          fi
